# Generated by Django 5.0.14 on 2026-04-08 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('clothing', 'Clothing'), ('tarpaulin', 'Tarpaulin'), ('dtf', 'DTF Transfer'), ('sticker', 'Sticker'), ('mug', 'Mug')], default='clothing', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('mockup_image', models.ImageField(blank=True, help_text='Base mockup image for the editor', null=True, upload_to='products/mockups/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Product-specific configuration (dimensions, print area, etc.)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_config', models.JSONField(help_text='Fabric.js canvas JSON data')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='designs/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2X Large'), ('3XL', '3X Large')], max_length=5)),
                ('color', models.CharField(max_length=50)),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost for this variant', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_variants', to='shop.product')),
            ],
            options={
                'ordering': ['size', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
