# Generated by Django 4.2.5 on 2026-04-25 00:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPrintVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('2x3', '2x3 (Wallet)'), ('3R', '3.5x5 (3R)'), ('4R', '4x6 (4R)'), ('5R', '5x7 (5R)'), ('6R', '6x8 (6R)'), ('8R', '8x10 (8R)'), ('A4', '8.27x11.69 (A4)')], max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=999)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('photo_print', 'Photo Print')], default='clothing', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClothingVariant',
        ),
        migrations.AddField(
            model_name='photoprintvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_variants', to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='photoprintvariant',
            unique_together={('product', 'size')},
        ),
    ]
