# Generated by Django 5.1.15 on 2026-05-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_featuretoggle_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('photo_print', 'Photo Print')], default='photo_print', max_length=20),
        ),
    ]
